name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  infrastructure_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Infrastructure and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Resource Group
        run: |
          az group create --name rg-static-proxy --location westeurope
      
      - name: Deploy Infrastructure
        id: infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-static-proxy
          template: infra/main.bicep
          parameters: staticWebAppName=static-web-app-sample location=westeurope
      
      - name: Get Deployment Token
        id: get-token
        run: |
          TOKEN=$(az staticwebapp secrets list --name "static-web-app-sample" --resource-group "rg-static-proxy" --query "properties.apiKey" --output tsv)
          echo "::add-mask::$TOKEN"
          echo "deployment-token=$TOKEN" >> $GITHUB_OUTPUT
      
      - name: Build And Deploy App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get-token.outputs.deployment-token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get Deployment Token
        id: get-token
        run: |
          TOKEN=$(az staticwebapp secrets list --name "static-web-app-sample" --resource-group "rg-static-proxy" --query "properties.apiKey" --output tsv)
          echo "::add-mask::$TOKEN"
          echo "deployment-token=$TOKEN" >> $GITHUB_OUTPUT
      
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get-token.outputs.deployment-token }}
          action: "close"
